-- Create Users Table
CREATE TABLE users (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	Email TEXT NOT NULL UNIQUE,
	Website TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);