// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type usersTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *usersTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("users").
func (v *usersTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *usersTableType) Columns() []string {
	return []string{"ID", "FirstName", "LastName", "Email", "Website", "CreatedAt", "UpdatedAt"}
}

// NewStruct makes a new struct for that view or table.
func (v *usersTableType) NewStruct() reform.Struct {
	return new(Users)
}

// NewRecord makes a new record for that table.
func (v *usersTableType) NewRecord() reform.Record {
	return new(Users)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *usersTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// UsersTable represents users view or table in SQL database.
var UsersTable = &usersTableType{
	s: parse.StructInfo{Type: "Users", SQLSchema: "", SQLName: "users", Fields: []parse.FieldInfo{{Name: "ID", Type: "int64", Column: "ID"}, {Name: "FirstName", Type: "string", Column: "FirstName"}, {Name: "LastName", Type: "string", Column: "LastName"}, {Name: "Email", Type: "string", Column: "Email"}, {Name: "Website", Type: "string", Column: "Website"}, {Name: "CreatedAt", Type: "*time.Time", Column: "CreatedAt"}, {Name: "UpdatedAt", Type: "*time.Time", Column: "UpdatedAt"}}, PKFieldIndex: 0},
	z: new(Users).Values(),
}

// String returns a string representation of this struct or record.
func (s Users) String() string {
	res := make([]string, 7)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "FirstName: " + reform.Inspect(s.FirstName, true)
	res[2] = "LastName: " + reform.Inspect(s.LastName, true)
	res[3] = "Email: " + reform.Inspect(s.Email, true)
	res[4] = "Website: " + reform.Inspect(s.Website, true)
	res[5] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[6] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Users) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.FirstName,
		s.LastName,
		s.Email,
		s.Website,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Users) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.FirstName,
		&s.LastName,
		&s.Email,
		&s.Website,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *Users) View() reform.View {
	return UsersTable
}

// Table returns Table object for that record.
func (s *Users) Table() reform.Table {
	return UsersTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Users) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Users) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Users) HasPK() bool {
	return s.ID != UsersTable.z[UsersTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Users) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int64(i64)
	} else {
		s.ID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = UsersTable
	_ reform.Struct = (*Users)(nil)
	_ reform.Table  = UsersTable
	_ reform.Record = (*Users)(nil)
	_ fmt.Stringer  = (*Users)(nil)
)

func init() {
	parse.AssertUpToDate(&UsersTable.s, new(Users))
}
